---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-preview
  labels:
    app: rollouts-demo
  annotations:
    consul.hashicorp.com/service-sync: 'true'
    consul.hashicorp.com/service-name: 'discovery-sellerads-rollouts-demo'
    consul.hashicorp.com/service-tags: 'app=rollouts-demo-service,team=discovery-sellerads,backend=http,internal-lb'   
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30962
  selector:
    app: rollouts-demo
  type: LoadBalancer
